#!/usr/bin/env bun
/**
 * Embed the skill tree into a TypeScript module.
 *
 * The skills are markdown on disk, but `bun compile` produces a single binary
 * with no filesystem alongside it — so the plugin writes them out at startup
 * from an embedded string map instead. That map has to be generated.
 *
 * This script exists because the previous generator did not. The header of the
 * file it produced said "AUTO-GENERATED by /tmp/gen-skills.ts", and /tmp is not
 * a place anyone else can regenerate from. The cost was not hypothetical: three
 * Fluent skills sat in the repo for weeks while the shipped binary carried 55
 * of 58, and nothing could have caught it.
 *
 * Run it after adding, renaming or deleting a skill:
 *   bun packages/skills/script/generate-embedded.ts
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const SKILLS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..")
const OUTPUT = join(SKILLS_DIR, "..", "opencode", "src", "plugin", "servicenow", "bundled-skills-data.ts")

/** Every file under a skill directory, keyed by its path relative to the tree. */
const collect = (dir: string, acc: Record<string, string> = {}): Record<string, string> => {
  for (const entry of readdirSync(dir)) {
    // `script` holds this generator; it is not a skill.
    if (entry === "script" || entry === "package.json" || entry.startsWith(".")) continue
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      collect(full, acc)
      continue
    }
    acc[relative(SKILLS_DIR, full)] = readFileSync(full, "utf8")
  }
  return acc
}

const skills = collect(SKILLS_DIR)
const names = new Set(Object.keys(skills).map((k) => k.split("/")[0]))

const header = `// AUTO-GENERATED by packages/skills/script/generate-embedded.ts — do not edit by hand.
// The ${names.size} bundled Serac skills embedded as a string map so they survive into the
// \`bun compile\` binary (a filesystem dir does not). The servicenow plugin's
// config hook writes these to the data dir at startup and points
// config.skills.paths there.
//
// Regenerate after changing any skill:
//   bun packages/skills/script/generate-embedded.ts
`

writeFileSync(OUTPUT, `${header}export const BUNDLED_SKILLS: Record<string, string> = ${JSON.stringify(skills)}\n`)
console.log(`embedded ${names.size} skills (${Object.keys(skills).length} files) -> ${relative(process.cwd(), OUTPUT)}`)
