#!/usr/bin/env bun
/**
 * Embed the skill tree into a TypeScript module.
 *
 * The skills are markdown on disk, but `bun compile` produces a single binary
 * with no filesystem alongside it — so a consumer that ships as a binary writes
 * them out at startup from an embedded string map instead. That map has to be
 * generated.
 *
 * This script exists because the previous generator did not. The header of the
 * file it produced said "AUTO-GENERATED by /tmp/gen-skills.ts", and /tmp is not
 * a place anyone else can regenerate from. The cost was not hypothetical: three
 * Fluent skills sat in the repo for weeks while the shipped binary carried 55
 * of 58, and nothing could have caught it.
 *
 * The output lands inside this package (`src/embedded.ts`), not inside the
 * consumer — the skills own their own artifact, so the consumer is free to
 * change or disappear.
 *
 * Run it after adding, renaming or deleting a skill:
 *   bun packages/skills/script/generate-embedded.ts
 *
 * `--check` regenerates in memory and exits non-zero if the checked-in file is
 * stale, without writing. That is the drift gate — adding a skill and
 * forgetting to regenerate is otherwise silent, which is exactly how the
 * 55-of-58 gap happened.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const SKILLS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..")
const OUTPUT = join(SKILLS_DIR, "src", "embedded.ts")

/** Every file under one skill directory, keyed by its path relative to the tree. */
const collect = (dir: string, acc: Record<string, string>): Record<string, string> => {
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".")) continue
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      collect(full, acc)
      continue
    }
    acc[relative(SKILLS_DIR, full)] = readFileSync(full, "utf8")
  }
  return acc
}

// A skill is a top-level directory with a SKILL.md in it. Anything else at the
// package root — script/, src/, package.json, tsconfig.json — is packaging, not
// content. Defining it by the marker file rather than by a denylist means new
// packaging files never leak into the embed. The Serac Portal's own sync script
// uses the same rule, so the two agree on what a skill is.
const skillNames = readdirSync(SKILLS_DIR)
  .filter((entry) => !entry.startsWith("."))
  .filter((entry) => statSync(join(SKILLS_DIR, entry)).isDirectory())
  .filter((entry) => existsSync(join(SKILLS_DIR, entry, "SKILL.md")))
  .sort()

const skills: Record<string, string> = {}
for (const name of skillNames) collect(join(SKILLS_DIR, name), skills)

const header = `// AUTO-GENERATED by packages/skills/script/generate-embedded.ts — do not edit by hand.
// The ${skillNames.length} bundled Serac skills embedded as a string map so they survive into a
// \`bun compile\` binary (a filesystem dir does not). A consumer that has a real
// filesystem should read the markdown tree directly — see skillsRoot() in ./root.ts.
//
// Regenerate after changing any skill:
//   bun packages/skills/script/generate-embedded.ts
`

const contents = `${header}export const BUNDLED_SKILLS: Record<string, string> = ${JSON.stringify(skills)}\n`

if (process.argv.includes("--check")) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : undefined
  if (current === contents) {
    console.log(`up to date: ${skillNames.length} skills (${Object.keys(skills).length} files)`)
    process.exit(0)
  }
  console.error(
    `${relative(process.cwd(), OUTPUT)} is stale — ${skillNames.length} skills (${Object.keys(skills).length} files) on disk.\n` +
      `Run: bun packages/skills/script/generate-embedded.ts`,
  )
  process.exit(1)
}

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, contents)
console.log(
  `embedded ${skillNames.length} skills (${Object.keys(skills).length} files) -> ${relative(process.cwd(), OUTPUT)}`,
)
