#!/usr/bin/env bun

import solidPlugin from "@opentui/solid/bun-plugin"
import matter from "gray-matter"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"

// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`https://models.dev/api.json`).then((x) => {
      if (!x.ok) throw new Error(`Failed to fetch models.dev API: ${x.status} ${x.statusText}`)
      return x.text()
    })

// Validate the fetched data is valid JSON before writing to source
try {
  JSON.parse(modelsData)
} catch {
  throw new Error("models.dev API returned invalid JSON — refusing to write to source")
}

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const skillsDir = path.join(dir, "src/bundled-skills")
const skillGlob = new Bun.Glob("**/SKILL.md")
const skills: { name: string; description: string; location: string; content: string }[] = []

for await (const match of skillGlob.scan({ cwd: skillsDir, absolute: true, onlyFiles: true })) {
  const raw = await Bun.file(match).text()
  const md = matter(raw)
  if (!md.data.name || !md.data.description) continue
  skills.push({
    name: String(md.data.name),
    description: String(md.data.description),
    location: "/" + path.relative(path.join(dir, "src"), match),
    content: md.content,
  })
}

await Bun.write(
  path.join(dir, "src/skill/bundled-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const bundled = ${JSON.stringify(skills)} as const\n`,
)
console.log(`Generated bundled-snapshot.ts (${skills.length} skills)`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
// Distribution prefix for build output dirs and release tarballs. Kept
// independent of pkg.name (a scoped name like @serac-labs/core would nest
// dist/ under a directory and break the release workflow's flat globbing).
const prefix = "serac"
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    prefix,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  // Use require.resolve to find the module in hoisted node_modules (monorepo support)
  const opentuiCorePath = path.dirname(require.resolve("@opentui/core/package.json"))
  const parserWorker = fs.realpathSync(path.join(opentuiCorePath, "parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(prefix, "bun") as any,
      outfile: `dist/${name}/bin/serac`,
      execArgv: [`--user-agent=serac/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`

  // Bundle MCP servers as standalone JS files (fully bundled, no external deps)
  console.log(`  bundling MCP servers for ${name}`)
  await $`mkdir -p dist/${name}/mcp`

  // Bundle servicenow-unified MCP server with all dependencies
  // IMPORTANT: Use target: "node" so the output works with both node and bun
  const snUnifiedResult = await Bun.build({
    entrypoints: ["../servicenow-mcp/src/servicenow-mcp-unified/index.ts"],
    outdir: `dist/${name}/mcp`,
    target: "node",
    format: "esm",
    naming: "servicenow-unified.js",
    minify: true,
  })
  if (!snUnifiedResult.success) {
    console.error("  Failed to bundle servicenow-unified:", snUnifiedResult.logs)
  }

  // Bundle enterprise-proxy MCP server with all dependencies
  // IMPORTANT: Use target: "node" so the output works with both node and bun
  const entProxyResult = await Bun.build({
    entrypoints: ["../servicenow-mcp/src/enterprise-proxy/server.ts"],
    outdir: `dist/${name}/mcp`,
    target: "node",
    format: "esm",
    naming: "enterprise-proxy.js",
    minify: true,
  })
  if (!entProxyResult.success) {
    console.error("  Failed to bundle enterprise-proxy:", entProxyResult.logs)
  }

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )

  // Ad-hoc sign darwin binaries when building on macOS. Unsigned arm64 binaries
  // distributed via npm get the com.apple.provenance xattr on install and are
  // killed by macOS without a signature. For Linux CI, the publish workflow
  // runs rcodesign after this step.
  if (item.os === "darwin" && process.platform === "darwin") {
    const bin = `dist/${name}/bin/serac`
    await $`codesign --remove-signature ${bin}`.nothrow().quiet()
    await $`codesign --force -s - ${bin}`
  }

  binaries[name] = Script.version
}

export { binaries }
